### ISSUE TITLE
Paragraphs

### ISSUE THREAD

**Issue by MartusiaM** [nameFactory/NameFactory#19]
- podział na paragrafy opisu imienia
- zwiększenie fontu opisu imienia

**Comment by PiotrFilarski** [comment]
zmienione, czeka na wdrożenie i przetestowania @MartusiaM zamknij jak się uda

**Comment by MartusiaM** [comment]
problem w tym, ze nie wiem jak te akapity nazywac, no więc co z tym orbimy w takim razie?

**Comment by Necior** [comment]
@MartusiaM, nie nazywamy ich. Poprawki już na masterze, z tego, co wiem. Zamykam. Jeśli się mylę, to się otworzy ponownie.
