### ISSUE TITLE
List of rankings: use Cards

### ISSUE THREAD

**Issue by Necior** [nameFactory/NameFactory#4]

**Comment by MartusiaM** [comment]
zrobilam tak ten RecyclerView zeby zamiast ListView mial LayoutManager GridView, zerknijcie czy myślicie, ze to jest ok? 
Jak coś to nie ma wgl w tych wszystkich fragmentach i tak dalej jeszcze zdanych animacji w stylu naciskania na przycisk itd. na razie są po prostu zwyczajnie te elementy dodane
